"""empty message

Revision ID: e0cee5b34f3b
Revises: 8e56f34ed2ab
Create Date: 2019-02-27 16:21:56.496718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cee5b34f3b'
down_revision = '8e56f34ed2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
